### ISSUE TITLE
AC_MSG_ERROR([libnfc >= $LIBNFC_REQUIRED_VERSION is mandatory

### ISSUE THREAD

**Issue by EnnioEvo** [vk496/mfoc#2] opened 2019-02-25 14:36 UTC
Hi, I have this problem, can you please help me?

```
root@kaliEvo:~/cartellona/mfoc# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
./configure: line 3930: syntax error near unexpected token `libnfc,'
./configure: line 3930: `PKG_CHECK_MODULES(libnfc, libnfc >= $LIBNFC_REQUIRED_VERSION, , AC_MSG_ERROR([libnfc >= $LIBNFC_REQUIRED_VERSION is mandatory.]))'
```

**Comment by vk496** [comment] 2019-02-28 16:03
Sorry, I can't reproduce your error.

Please, send me this info:
```
$ lsb_release -a
$ autoreconf --version
```

And make sure you are on last commit of `hardnested` branch

**Comment by EnnioEvo** [comment] 2019-03-01 22:44
Yes, thanks
```
root@kali:~/mfoc# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.1
Codename:	n/a
root@kali:~/mfoc# autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```
I think I'm in the right branch, all I've done is 
`git clone https://github.com/vk496/mfoc.git`
and then the commands you wrote.
I install autotools by
`sudo apt-gen install autogen autoconf libtool`

**Comment by vk496** [comment] 2019-03-02 10:16
Please, try with:

git clone -b hardnested https://github.com/vk496/mfoc.git

**Comment by EnnioEvo** [comment] 2019-03-02 17:48
It worked, thank you, I discovered I cannot use git.

**Comment by jvenis** [comment] 2019-05-06 17:11
hi, i have the same problem. can you explain me what i have to do after doing: git clone -b hardnested https://github.com/vk496/mfoc.git

**Comment by aveklan** [comment] 2019-05-20 17:29
hi, same issue here.  I try this one git clone -b hardnested https://github.com/vk496/mfoc.git but i have the same error.

**Comment by jvenis** [comment] 2019-05-20 17:57
@aveklan use the miLazyCracker tool which  is working without problem. You can find it here on GitHub

**Comment by vk496** [comment] 2019-05-20 18:43
Please, make sure you installed `pkg-config` package in your system before executing `autoreconf -is`.

I will close this issue. Feel free to open it again if the error persist.

**Closed as completed by vk496** 2019-05-20 18:43 UTC

**Comment by EnnioEvo** [comment] 2019-05-20 19:23
This hardnested is far better than the one of MiLazyCracker, is more then 10 times faster.
